app/comment/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class DeleteForm(Form):
    submit = SubmitField('Yes')


class CommentForm(Form):
    body = StringField('', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/post/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class DeleteForm(Form):
    submit = SubmitField('Yes')


class CommentForm(Form):
    body = StringField('', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/comment/__init__.py
from flask import Blueprint

comment = Blueprint('comment', __name__)

from . import views

app/comment/views.py
"""
.. module:: comment.views.

   :synopsis: Handles all comment URL endpoints for the
   intranet application
"""
from app.comment import comment
from app.comment.forms import DeleteForm, CommentForm
from app.db_helpers import create_object, delete_object
from app.models import Post, Permission, Comment
from app.decorators import permission_required
from flask import render_template, redirect, url_for, abort, flash
from flask_login import login_required, current_user


@comment.route('/moderate/<int:id>', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate(id):
    """
    Return the moderation page for comments from a specific post.

    Keyword arguments:
    id -- the post id
    """
    avatar = current_user.avatar
    post = Post.query.get_or_404(id)
    allComments = []
    comments = post.comments
    for comment in comments:
        allComments.append(comment)
    allComments.reverse()
    allCommentsCount = len(allComments)
    return render_template('comment/moderate.html', post=post.id, avatar=avatar, allComments=allComments,
                           allCommentsCount=allCommentsCount)


@comment.route('/moderate/enable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_enable(id):
    """
    Enable a comment and redirect to the moderation page.

    Keyword arguments:
    id -- the comment id
    """
    comment = Comment.query.get_or_404(id)
    comment.disabled = False
    create_object(comment)
    post = Comment.query.filter_by(id=id).first().post
    return redirect(url_for('comment.moderate', id=post.id))


@comment.route('/moderate/disable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_disable(id):
    """
    Disable a comment and redirect to the moderation page.

    Keyword arguments:
    id -- the comment id
    """
    comment = Comment.query.get_or_404(id)
    comment.disabled = True
    create_object(comment)
    post = Comment.query.filter_by(id=id).first().post
    return redirect(url_for('comment.moderate', id=post.id))


@comment.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_comment(id):
    """
    Return the page for editing a specific comment.

    Keyword arguments:
    id -- the comment id
    """
    comment = Comment.query.get_or_404(id)
    form = CommentForm()
    if current_user != comment.author and not current_user.can(Permission.COMMENT):
        abort(403)
    if form.validate_on_submit():
        if "[Edited]" not in form.body.data:
            comment.body = "[Edited] " + form.body.data
        else:
            comment.body = form.body.data
        create_object(comment)
        flash('The comment has been updated.')
        return redirect(url_for('post.view_post', id=comment.post_id))
    form.body.data = comment.body
    return render_template('comment/edit_comment.html', form=form, comment=comment)


@comment.route('/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_comment(id):
    """
    Return the confirmation page for deleting a comment.

    Keyword arguments:
    id -- the comment id
    """
    comment = Comment.query.get_or_404(id)
    form = DeleteForm()
    if current_user != comment.author and not current_user.can(Permission.COMMENT):
        abort(403)
    if form.validate_on_submit():
        delete_object(comment)
        flash('The comment has been deleted.')
        return redirect(url_for('post.view_post', id=comment.post_id))
    return render_template('comment/delete_comment.html', form=form, comment=comment)

app/post/__init__.py
from flask import Blueprint

post = Blueprint('post', __name__)

from . import views

app/post/views.py
"""
.. module:: post.views.

   :synopsis: Handles all post URL endpoints for the
   intranet application
"""
import datetime
import os
from datetime import timedelta, datetime
from os import listdir
from os import environ
from os.path import isfile, join
from app import db
from app.post import post
from app.models import Post, Tag, Permission, PostTag, Comment
from app.db_helpers import create_object, delete_object, allowed_post_file
from app.decorators import permission_required
from app.post.forms import DeleteForm, CommentForm
from flask import render_template, redirect, url_for, abort, flash, request
from flask_login import login_required, current_user
from werkzeug import secure_filename


@post.route('/new_post', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.WRITE_ARTICLES)
def new_post(data=None):
    """
    Return the page for creating a new post containing tags, title, and text.

    Keyword arguments:
    data -- initialization of data (default None)
    """
    # tag_list = Tag.query.with_entities(Tag.name).all()
    # tag_list = [r[0].encode('utf-8') for r in tag_list]
    if data or request.method == 'POST':
        data = request.form.copy()
        post = Post.query.filter_by(text=data['editor1']).first()
        if data['editor1'] == "":
            return render_template('error.html', message="Please fill out the text.")
        if post is None:
            # if data['input_tag'] == '':
            #     return render_template('error.html', message="Please include tags!")
            title = data['input_title']
            text = data['editor1']
            file = request.files['post_file']
            if len(text) > 8000:
                return render_template('error.html',
                                       message='Text is too long. Please lower number of characters or remove some text formatting.')
            time = datetime.now()
            post = Post(title=title, text=text, time=time, author=current_user._get_current_object())
            create_object(post)
            if len(file.filename) > 0:
                post_file = "postid" + str(post.id) + "_" + secure_filename(file.filename.replace(" ", "_"))
                save_address = os.path.join(os.environ.get('UPLOAD_POST_FILE_FOLDER'), post_file)
                # print(save_address)
                if allowed_post_file(file.filename):
                    # if post.file is not None:
                    #     old_file = os.path.join(os.environ.get('UPLOAD_POST_FILE_FOLDER'), post.file)
                    #     if os.path.exists(old_file):
                    #         os.remove(old_file)
                    file.save(save_address)
                    post.file = "postid" + str(post.id) + "_" + str(file.filename.replace(" ", "_"))
                    db.session.commit()
                    # post_folder_files = [f for f in listdir(os.environ.get('UPLOAD_POST_FILE_FOLDER')) if
                    #                      isfile(join(os.environ.get('UPLOAD_POST_FILE_FOLDER'), f))]
                    # print(post_folder_files)
                else:
                    return render_template('error.html', message="Please upload a valid file type.")
        # tag_split = data['input_tag'].split(', ')
        # for each_tag in tag_split:
        #     if Tag.query.filter_by(name='').first() != None:
        #         delete_object(Tag.query.filter_by(name='').first())
        #     if each_tag[0] != '#':
        #         each_tag = '#' + each_tag
        #     if each_tag not in tag_list:
        #         newtag = Tag(name=each_tag)
        #         create_object(newtag)
        #         posttag = PostTag(post_id=post.id, tag_id=newtag.id)
        #         create_object(posttag)
        #     else:
        #         oldtag = Tag.query.filter_by(name=each_tag).first().id
        #         posttag = PostTag(post_id=post.id, tag_id=oldtag)
        #         create_object(posttag)
        return redirect(url_for('main.index'))
    # return render_template('post/new_post.html', tag_list=tag_list)
    return render_template('post/new_post.html')


@post.route('/<int:id>', methods=['GET', 'POST'])
def view_post(id):
    """
    Return the page of a specific post containing the post itself, comments, and comment box if logged in.

    Keyword arguments:
    id -- the post id
    """
    post = Post.query.get_or_404(id)
    page_posts = []
    if post.author is None:
        author = ''
    else:
        author = post.author.first_name + ' ' + post.author.last_name
    post_tags = PostTag.query.filter_by(post_id=post.id).all()
    tags = []
    for tag in post_tags:
        name = Tag.query.filter_by(id=tag.tag_id).first().name
        tag = {
            'id': tag.tag_id,
            'name': name
        }
        tags.append(tag)
    single_post = {
        'id': post.id,
        'title': post.title,
        'time': post.time.strftime("%B %d, %Y %l:%M%p %Z"),
        'text': post.text,
        'comments': post.comments.count(),
        'tags': tags,
        'author': author,
        'file': post.file
    }
    page_posts.append(single_post)
    form = CommentForm()
    allComments = []
    for comment in post.comments:
        allComments.append(comment)
    allComments.reverse()
    allCommentsCount = len(allComments)
    if form.validate_on_submit():
        comment = Comment(body=form.body.data, post=post, author=current_user._get_current_object())
        create_object(comment)
        flash('Your comment has been posted.')
        return redirect(url_for('post.view_post', id=post.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() - 1) / \
               int(os.environ.get('COMMENTS_PER_PAGE')) + 1
    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=int(os.environ.get('COMMENTS_PER_PAGE')), error_out=False)
    comments = pagination.items
    return render_template('post/post.html', post=post, posts=[post], form=form, allComments=allComments,
                           allCommentsCount=allCommentsCount, comments=comments, pagination=pagination,
                           page_posts=page_posts)


@post.route('/tag/<string:tag>', methods=['GET', 'POST'])
def tag(tag):
    """
    Return the page containing all posts with the chosen tag.

    Keyword arguments:
    tag -- the selected tag
    """
    page_posts = []
    tagid = Tag.query.filter_by(name=tag).first().id
    posttags = PostTag.query.filter_by(tag_id=tagid).all()
    posts = []
    for posttag in posttags:
        post = Post.query.filter_by(id=posttag.post_id).first()
        posts.append(post)
    posts.reverse()
    for post in posts:
        if post.author is None:
            author = ''
        else:
            author = post.author.first_name + ' ' + post.author.last_name
        post_tags = PostTag.query.filter_by(post_id=post.id).all()
        tags = []
        for tag in post_tags:
            name = Tag.query.filter_by(id=tag.tag_id).first().name
            tag = {
                'id': tag.tag_id,
                'name': name
            }
            tags.append(tag)
        post = {
            'id': post.id,
            'title': post.title,
            'time': post.time.strftime("%B %d, %Y %l:%M%p %Z"),
            'text': post.text,
            'comments': post.comments.count(),
            'tags': tags,
            'author': author,
            'file': post.file
        }
        page_posts.append(post)
    return render_template('post/tagged_posts.html', page_posts=page_posts)


@post.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    """
    Return the page for editing a specific post containing possible edits for tags, title, and text.

    Keyword arguments:
    id -- the post id
    """
    # tag_list = Tag.query.with_entities(Tag.name).all()
    # tag_list = [r[0].encode('utf-8') for r in tag_list]
    # previous_tag_string = ""
    # previous_tag_list = []
    # postids = PostTag.query.filter_by(post_id=id).all()
    # for postid in postids:
    #     tagid = postid.tag_id
    #     tagname = Tag.query.filter_by(id=tagid).first().name
    #     previous_tag_list.append(tagname)
    #     previous_tag_string += tagname
    #     previous_tag_string += ", "
    # previous_tag_string = previous_tag_string[:-2]
    post = Post.query.get_or_404(id)
    if current_user != post.author and not current_user.can(Permission.ADMINISTER):
        abort(403)
    if request.method == 'POST':
        data = request.form.copy()
        post.title = data['input_title']
        post.text = data['editor1']
        create_object(post)
        file = request.files['post_file']
        if len(file.filename) > 0:
            post_file = "postid" + str(post.id) + "_" + secure_filename(file.filename.replace(" ", "_"))
            save_address = os.path.join(os.environ.get('UPLOAD_POST_FILE_FOLDER'), post_file)
            # print("save_address: ", save_address)
            if allowed_post_file(file.filename):
                if post.file is not None:
                    old_file = os.path.join(os.environ.get('UPLOAD_POST_FILE_FOLDER'), post.file)
                    if os.path.exists(old_file):
                        os.remove(old_file)
                file.save(save_address)
                post.file = "postid" + str(post.id) + "_" + str(file.filename.replace(" ", "_"))
                db.session.commit()
                # post_folder_files = [f for f in listdir(os.environ.get('UPLOAD_POST_FILE_FOLDER')) if
                #                      isfile(join(os.environ.get('UPLOAD_POST_FILE_FOLDER'), f))]
                # print(post_folder_files)
            else:
                return render_template('error.html', message="Please upload a valid file type.")
        # tag_split = data['input_tag'].split(', ')
        # for each_tag in tag_split:

app/templates/_comments.html
{{ moment.include_moment() }}

{% if allCommentsCount > 0 %}
    {% for comment in allComments %}
        <div class="well">
            <div id="comment-body">
                {% if comment.disabled %}
                    <p><i>This comment has been disabled by a moderator.</i></p>
                {% endif %}

                {% if moderate or not comment.disabled %}
                    <h4>
                        {% if comment.body_html %}
                            <a href="{{ url_for('user.profile', email=comment.author.email) }}">
                                <img src="{{ url_for('static', filename=comment.author.avatar) }}" height="35"
                                     width="35">
                            </a>
                            {{ comment.author.first_name }} {{ comment.author.last_name }} -
                            {{ moment(comment.timestamp).fromNow() }}
                            <br>
                            <div class="well">
                                {{ comment.body_html }}
                            </div>
                        {% else %}
                            <div class="well">
                                {{ comment.body }}
                            </div>
                        {% endif %}
                    </h4>
                    {% if current_user == comment.author or current_user.is_administrator() %}
                        <a href="{{ url_for('comment.edit_comment', id=comment.id) }}">
                            <span class="label label-primary">Edit</span>
                        </a>
                        <a href="{{ url_for('comment.delete_comment', id=comment.id) }}">
                            <span class="label label-danger">Delete</span>
                        </a>
                    {% endif %}
                {% endif %}

                {% if moderate %}
                    {% if comment.disabled %}
                        <a class="label label-primary" href="{{ url_for('comment.moderate_enable',
                            id=comment.id, page=page) }}">Enable</a>
                    {% else %}
                        <a class="label label-danger" href="{{ url_for('comment.moderate_disable',
                            id=comment.id, page=page) }}">Disable</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% else %}
    <div class="well">
        <h4>There are currently no comments for this post.</h4>
    </div>
{% endif %}

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint,
            page = pagination.page - 1) }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p) }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p) }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint,
            page = pagination.page + 1) }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/_posts.html
{% if page_posts[0] %}
    {% for post in page_posts %}
        <div class="well">
            <h2>{{ post['title'] }}</h2>
            <h10>{{ post['time'] }}</h10>
            <br>
            {% if 'Twitter - @nycrecords: ' in post['title'] %}
                <h13>Posted on Twitter</h13>
            {% elif post['author'] == '' %}

            {% else %}
                <h13>Posted by {{ post['author'] }}</h13>
            {% endif %}
            <div class="well">
                {{ post['text'] | safe }}
                {% if post['file'] != None %}
                    Attachment: <a href="/static/post_files/{{ post['file'] }}"
                                  target="_blank">{{ post['file'].split('_', 1)[-1] }}</a>
                {% endif %}
            </div>
            <div class="post-footer">
                <a href="{{ url_for('post.view_post', id=post['id']) }}">
                    <span class="label label-default">Permalink</span>
                </a>
                <a href="{{ url_for('post.view_post', id=post['id']) }}#comments">
                    <span class="label label-primary">{{ post['comments'] }} Comments</span>
                </a>
                {#                {% for tag in post['tags'] %}#}
                {#                    <a href="{{ url_for('post.tag', tag=tag['name']) }}">#}
                {#                        <span class="label label-primary">{{ tag['name'] }}</span>#}
                {#                    </a>#}
                {#                {% endfor %}#}
                {% if current_user.is_authenticated %}
                    {% if current_user.first_name + ' ' + current_user.last_name == post['author'] %}
                        <a href="{{ url_for('post.edit', id=post['id']) }}">
                            <span class="label label-primary">Edit</span>
                        </a>
                        <a href="{{ url_for('post.delete', id=post['id']) }}">
                            <span class="label label-danger">Delete</span>
                        </a>
                    {% elif current_user.is_administrator() %}
                        <a href="{{ url_for('post.edit', id=post['id']) }}">
                            <span class="label label-primary">Edit [Admin]</span>
                        </a>
                        <a href="{{ url_for('post.delete', id=post['id']) }}">
                            <span class="label label-danger">Delete</span>
                        </a>
                    {% endif %}
                {% endif %}
                <br>
            </div>
        </div>
    {% endfor %}
{% else %}
    <h4>There are no matching results.</h4>
{% endif %}

app/templates/agency_policies.html
{% extends 'layouts/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Intranet - Agency Policies{% endblock %}

{% block body %}
<div class="well">
    <h2>Agency Policies</h2>
</div>

<div class="well">
	<h4><b>Policies</b>
	<br><br>
	- <a href="{{ url_for('static', filename='files/Employee_Leave_Request.pdf') }}">Employee Leave Request</a><br>
	- <a href="{{ url_for('static', filename='files/Onboarding_Policy_and_Procedure.pdf') }}">Onboarding Policy and Procedure</a><br>
	</h4>
</div>
{% endblock %}

app/templates/eeo.html
{% extends 'layouts/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Intranet - EEO{% endblock %}

{% block body %}
<div class="well">
    <h2>Equal Employment Opportunity</h2>
</div>

<div class="well">
	<h4><b>EEO Information Files</b>
	<br><br>
	- <a href="{{ url_for('static', filename='files/NYC_EEO_Policy.pdf') }}">NYC EEO Policy</a><br>
	- <a href="{{ url_for('static', filename='files/Addendum_to_the_EEO_Policy.pdf') }}">NYC EEO Policy Addendum</a><br>
	- <a href="{{ url_for('static', filename='files/eeo_reasonable_accommodation.pdf') }}">EEO Reasonable Accommodation</a><br>
	- <a href="{{ url_for('static', filename='files/eeo_discrimination_complaint_procedures.pdf') }}">EEO Discrimination Complaint Procedures</a><br>
	- <a href="{{ url_for('static', filename='files/about_eeo_booklet.pdf') }}">About EEO Booklet</a><br>
	- <a href="{{ url_for('static', filename='files/55A_Booklet_final.pdf') }}">55A Booklet Final</a><br>
	- <a href="{{ url_for('static', filename='files/EO16Poster_FINAL.pdf') }}">Executive Order 16 Poster</a><br>
	</h4>
</div>
{% endblock %}

app/templates/enfg.html
{% extends 'layouts/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block scripts %}
<script type="text/javascript">
    function open_fun() {
        document.getElementById('link').innerHTML = "<a " +
            "class='btn btn-default' href='javascript:clo_fun()'>Remove " +
            "All</a>";
{#        var aa = document.querySelectorAll("input[type=checkbox]");#}
        var aa = document.getElementsByName("borough");
        for (var i = 0; i < aa.length; i++){
            aa[i].checked = true;
        }
    }
    function clo_fun() {
        document.getElementById('link').innerHTML = "<a " +
            "class='btn btn-default' href='javascript:open_fun()'>All " +
            "Boroughs</a>";
{#        var aa = document.querySelectorAll("input[type=checkbox]");#}
        var aa = document.getElementsByName("borough");
        for (var i = 0; i < aa.length; i++){
            aa[i].checked = false;
        }
    }

    function bride() {
        var bride = document.getElementById("bride");
        var marriage = document.getElementById("type-2");
        var marriageLicense = document.getElementById("type-3");
        bride.style.display = 'none';

        if (marriage.checked == true) {
            bride.style.display = 'block';
        }

    }
</script>
{% endblock %}

{% block title %}Intranet - ENFG{% endblock %}

{% block body %}
<div class="well">
    <h2>Easy Not Found Generator</h2>
</div>

<form class="form" role="form" method="post">
    {{ form.csrf_token }}
    {{ form.type.label }}<br />
    {{ form.type(class="form-control") }}
    {{ form.name.label }}<br />
    {{ form.name(class="form-control") }}
    <div id="bride" style="display: hidden;">
        {{ form.bride_name.label }}<br />
        {{ form.bride_name(class="form-control") }}
    </div>
    {{ form.year.label }}<br />
    {{ form.year(class="form-control") }}
    {{ form.borough.label }}<br />
    {{ form.borough(class="form-control") }}
    <div id='link'>
        <a class="btn btn-default" href='javascript:open_fun()'>All Boroughs</a>
    </div>
    <br />
    {{ form.signature.label }} {{ form.signature() }}<br /><br />
    {{ form.submit(class="btn btn-default btn-lg") }}
</form>
{% endblock %}

app/templates/error.html
{% extends 'layouts/base.html' %}
{% import "_macros.html" as macros %}

{% block title %}Intranet - Error Page{% endblock %}

{% block body %}
<div class="well">
    <h2>Something went wrong...</h2>
</div>
<div class="well">
	<h4>{{ message }}</h4>
</div>
{% endblock %}

app/templates/index.html
{% extends 'layouts/base.html' %}
{% import "_macros.html" as macros %}

{% block title %}Intranet - Home{% endblock %}

{% block body %}
<div id="nav-bottomright" style="float: right;">
        <form name="input" class="form-horizontal" id="searchTags" method="post">
            <div class="control-group">
                <div class="ui action input">
                    <input name="search_term" type="text" placeholder="Search Posts" style="font-family: Georgia, serif;">
                    <select name="select_search_option" class="ui compact selection dropdown">
                        <option value="all">All</option>
                        <option value="title">Title</option>
                        <option value="text">Text</option>
                    </select>
                </div>
            </div>
{#            <div class="control-group">#}
{#            <select name="select_tags" class="ui fluid search dropdown" multiple=" ">#}
{#                <option value="">Tag Filter</option>#}
{#                {% for tag in all_tags %}#}
{#                <option value="{{ tag.name }}">{{ tag.name }}</option>#}
{#                {% endfor %}#}
{#            </select>#}
{#            </div>#}
            <div id="requestButton" class="control-group">
                <div>
                    <button type="submit" title="search_tags" class="ui button" style="float: right;">Search</button>
                </div>
            </div>
        </form>
    </div>

<div class="well">
    <h1>Home</h1>
</div>

{#{% if pagination.page == 1 %}#}
{#<div id="tweets">#}
{#    <div class="well">#}
{#    <h2>Twitter Ticker</h2>#}
{#    {% for tweet in recent_tweet %}#}
{#        <a href="https://twitter.com/nycrecords/">@{{ tweet.user.screen_name }}</a><br>#}
{#        {{ tweet_datetime }}<br>#}
{#        <div class="well">#}
{#            {{ tweet.text }}#}
{#        </div>#}
{#    {% endfor %}#}
{#    <a href="{{ url_for('main.tweets') }}">View Recent Tweets</a>#}
{#    </div>#}
{#</div>#}
{#{% endif %}#}

{% include '_posts.html' %}

<div id="newpost">
    {% if current_user.is_administrator() or current_user.is_director() %}
    <h3><a href="{{ url_for('post.new_post') }}">Add Post</a></h3>
    {% endif %}
</div>

{{ macros.pagination_widget(pagination, '.index') }}

{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery-1.10.2.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/semantic.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/semantic.min.js') }}"></script>
<script type="text/javascript">
$('.ui.dropdown')
    .dropdown();
</script>
{% endblock %}

app/templates/library.html
{% extends 'layouts/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Intranet - Municipal Library{% endblock %}

{% block body %}
<div class="well">
    <h2>Municipal Library</h2>
</div>

<div class="well">
	<h4><b>There is currently nothing available. Please check back soon!</b>
</div>
{% endblock %}

app/templates/lmt.html
{% extends 'layouts/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Intranet - LMT{% endblock %}

{% block body %}
<div class="well">
    <h2>Labor Management Team</h2>
</div>

<div class="well">
	<h4><b>Meeting Minutes</b>
	<br><br>
	- <a href="{{ url_for('static', filename='files/LMT_12_17_2015.pdf') }}">12-17-2015</a><br>
	- <a href="{{ url_for('static', filename='files/LMT_10_15_2015.pdf') }}">10-15-2015</a><br>
	- <a href="{{ url_for('static', filename='files/LMT_09_17_2015.pdf') }}">09-17-2015</a><br>
	- <a href="{{ url_for('static', filename='files/LMT_07_16_2015.pdf') }}">07-16-2015</a><br>
	- <a href="{{ url_for('static', filename='files/LMT_06_18_2015.pdf') }}">06-18-2015</a><br>
	- <a href="{{ url_for('static', filename='files/LMT_05_20_2015.pdf') }}">05-20-2015</a><br>
	- <a href="{{ url_for('static', filename='files/LMT_04_16_2015.pdf') }}">04-16-2015</a><br>
	- <a href="{{ url_for('static', filename='files/LMT_03_19_2015.pdf') }}">03-19-2015</a><br>
	- <a href="{{ url_for('static', filename='files/LMT_02_19_2015.pdf') }}">02-19-2015</a><br>
	- <a href="{{ url_for('static', filename='files/LMT_01_15_2015.pdf') }}">01-15-2015</a><br>
	- <a href="{{ url_for('static', filename='files/LMT_12_18_2014.pdf') }}">12-18-2014</a><br>
	- <a href="{{ url_for('static', filename='files/LMT_11_20_2014.pdf') }}">11-20-2014</a><br>
	- <a href="{{ url_for('static', filename='files/LMT_10_01_2014.pdf') }}">10-01-2014</a><br>
	</h4>
</div>
{% endblock %}

app/templates/tweets.html
{% extends 'layouts/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Intranet - Tweets{% endblock %}

{% block body %}
<div class="well">
    <h2>Recent Tweets</h2>
    <a href="https://twitter.com/nycrecords/"><h5>@nycrecords</h5></a>
</div>

<div class="well">
	{% for tweet in previous_tweets %}
        {{ tweet.time }}<br>
        <div class="well">
            {{ tweet.text }}<br>
        </div>
    {% endfor %}
</div>
{% endblock %}